### ISSUE TITLE
Data model recommendations

### ISSUE THREAD

**Issue by arwhyte** [ashleyschoo/hospital-pricing#1]
### Naming Conventions
Follow Simon Holywell's https://www.sqlstyle.guide/.  
* Use lowercase for all table names and properties

### Table names
Name tables after the entity not properties of an entity (e.g., `hospital` not `hospital_name`).
* Change `hospital_name` to `hospital`.

### Table consolidation
* Migrate the address info out of `hospital_address` and into `hospital`.  

### Foreign keys
* Drop the table_name prefixes from all foreign key names (e.g., `hospital_ownership_hospital_ownership_id` to `hospital_ownership_id`).
* Add `city.state_id` foreign key.  Then you can remove the `state_id` FK from the `hospital_address` table (which you will consolidate with the `hospital` table).

### Other questions
* What is the purpose of the `zip_code_designation` table?

Let's find some time later this week to discuss the data model in order to ensure that it's footprint is as small as possible.

**Comment by ashleyschoo** [comment]
![image](https://user-images.githubusercontent.com/30761294/49095384-5dc2bf80-f236-11e8-8980-e8bf272b1a91.png)

I changed the capitalization of the table names and properties, moved the hospital_address table into hospital, removed the hospital ownership table, and fixed the foreign key names.
The zip_code_designation identifies zip codes that have a physician shortage or high poverty rates and addresses the population health aspect of healthcare access when comparing prices vs quality.

**Comment by arwhyte** [comment]
Looking better.

**Comment by ashleyschoo** [comment]
updated model
