### ISSUE TITLE
Add link to data set in README

### ISSUE THREAD

**Issue by arwhyte** [ashleyschoo/hospital-pricing#2]
Add a link the Kaggle data set you are using in the README.  This one, yes?

https://www.kaggle.com/center-for-medicare-and-medicaid/hospital-ratings

**Comment by arwhyte** [comment]
Actually, on review it's this one:

https://data.cms.gov/Medicare-Inpatient/Inpatient-Prospective-Payment-System-IPPS-Provider/97k6-zzx3

**Comment by ashleyschoo** [comment]
Added both links to both datasets to the readme.
